### ISSUE TITLE
Install on hidden directory

### ISSUE THREAD

**Issue by zeehio** [hafen/rminiconda#1]
Hi,

I just saw a tweet pointing to this package and I am considering using it. Thanks!

Linux users would probably appreciate the install path to be `~/.rminiconda` (notice the leading dot) so the directory is hidden. With respect to installation paths, the Tinytex package https://yihui.name/tinytex/ has reasonable installation paths for all OSs, maybe that is worth considering.

This is just a suggestion, feel free to close the issue :-)

**Comment by hafen** [comment]
That's a great suggestion. That was the part I was most unsure of in the current implementation. I'll update it to use this same path scheme and that way the path will always be consistent and in a reasonable OS-specific place.
