### ISSUE TITLE
install_miniconda error

### ISSUE THREAD

**Issue by ndrubins** [hafen/rminiconda#14]
Hi,
I'm following [this stackoverflow post](https://stackoverflow.com/questions/74151654/error-cannot-install-miniconda-with-rstudio) but executing `rminiconda::install_miniconda(name='your_name')` gives me this error:
```
Error in utils::download.file(paste0(base_url, inst_file), inst_file,  : 
  download from 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh' failed
In addition: Warning messages:
1: In utils::download.file(paste0(base_url, inst_file), inst_file,  :
  downloaded length 26458487 != reported length 72930976
2: In utils::download.file(paste0(base_url, inst_file), inst_file,  :
  URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh': Timeout of 60 seconds was reached
```

But 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh'  exists and can be downloaded.

Is there a way to point `rminiconda::install_miniconda` to a pre downloaded `Miniconda3-latest-MacOSX-x86_64.sh` file?

**Comment by hafen** [comment]
Sorry for the delay - I hope you found a resolution to your issue. I just tried the command to see if something has changed but it worked and I cannot replicate this error. I wonder if your internet connection temporarily went out or something.

**Comment by ndrubins** [comment]
Thanks for the response. Yeah, I managed to work it out.

**Comment by hafen** [comment]
Great!
